import { useState, useEffect, useContext } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { Image as ImageIcon, Download, Share2, Loader2, Sparkles, Plus } from 'lucide-react';
import { AuthContext } from '../context/AuthContext';

export default function Gallery() {
  const [images, setImages] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const { user, token } = useContext(AuthContext);
  const navigate = useNavigate();

  useEffect(() => {
    if (!token) {
      navigate('/login');
      return;
    }

    const fetchGallery = async () => {
      try {
        const res = await fetch(`${import.meta.env.VITE_API_URL || "http://localhost:5000"}` + '/api/gallery', {
          headers: {
            'Authorization': `Bearer ${token}`
          }
        });
        const data = await res.json();
        if (!res.ok) throw new Error(data.error || 'Failed to fetch gallery');
        setImages(data);
      } catch (err) {
        setError(err.message);
      } finally {
        setLoading(false);
      }
    };

    fetchGallery();
  }, [token, navigate]);

  const handleDownload = async (imageUrl, prompt) => {
    try {
      const response = await fetch(imageUrl);
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      // create a clean filename from prompt
      const cleanPrompt = prompt.replace(/[^a-zA-Z0-9]/g, '_').substring(0, 30);
      link.download = `AI_${cleanPrompt}_${Date.now()}.jpg`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    } catch (err) {
      alert("Download failed. Please right-click the image and save as.");
    }
  };

  const handleShare = async (imageId) => {
    const shareUrl = `${window.location.origin}/share/${imageId}`;
    try {
      await navigator.clipboard.writeText(shareUrl);
      alert(`Shareable link copied to clipboard!\n\n${shareUrl}`);
    } catch (err) {
      alert("Failed to copy URL. Here is your link:\n" + shareUrl);
    }
  };

  if (loading) {
    return (
      <div className="min-h-[70vh] flex flex-col items-center justify-center gap-4">
        <Loader2 className="w-12 h-12 text-blue-500 animate-spin" />
        <p className="text-gray-400 font-medium animate-pulse">Loading your personal gallery...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-[70vh] flex flex-col items-center justify-center gap-4 text-center px-4">
        <div className="p-6 rounded-2xl bg-red-500/10 border border-red-500/20 text-red-400 max-w-md">
          <h3 className="text-lg font-bold mb-2">Oops! Something went wrong</h3>
          <p className="text-sm">{error}</p>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-7xl mx-auto px-4 py-12">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-6 mb-12 border-b border-purple-900/50 pb-8">
        <div>
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-pink-500/10 text-pink-400 border border-pink-500/20 text-xs font-semibold mb-3">
            <Sparkles size={14} />
            Private Collection
          </div>
          <h1 className="text-4xl font-extrabold tracking-tight text-white">
            Your Personal <span className="bg-clip-text text-transparent bg-gradient-to-r from-purple-400 via-fuchsia-400 to-pink-400">Gallery</span>
          </h1>
          <p className="text-purple-200/70 text-sm mt-2">All the stunning AI creations generated by you.</p>
        </div>

        <Link 
          to="/dashboard" 
          className="btn-premium inline-flex items-center gap-2 px-6 py-3 rounded-xl text-white font-bold shadow-lg shadow-purple-500/30 transition transform hover:scale-105 self-start md:self-auto border border-white/20"
        >
          <Plus size={20} /> Generate New Image
        </Link>
      </div>

      {/* Gallery Grid */}
      {images.length === 0 ? (
        <div className="text-center py-20 px-4 rounded-3xl glass-card border border-purple-800/50 flex flex-col items-center justify-center gap-6 max-w-2xl mx-auto bg-purple-950/20 backdrop-blur-xl">
          <div className="w-20 h-20 rounded-full bg-purple-950/60 flex items-center justify-center text-purple-400/60 border border-purple-800/50 shadow-inner">
            <ImageIcon size={40} />
          </div>
          <div>
            <h3 className="text-2xl font-bold text-white mb-2">No images generated yet</h3>
            <p className="text-purple-200/70 max-w-md mx-auto text-sm leading-relaxed font-light">
              Your gallery is currently empty. Head over to the dashboard, enter a prompt, and let the AI bring your imagination to life!
            </p>
          </div>
          <Link 
            to="/dashboard" 
            className="btn-premium px-8 py-4 rounded-xl text-white font-bold transition shadow-lg shadow-purple-500/30 border border-white/20 transform hover:scale-105 active:scale-95"
          >
            Start Creating Now
          </Link>
        </div>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
          {images.map((img) => (
            <div 
              key={img._id} 
              className="group relative rounded-3xl overflow-hidden glass-card border border-purple-800/40 shadow-xl hover:shadow-2xl hover:border-pink-500/50 transition-all duration-300 flex flex-col bg-purple-950/20"
            >
              {/* Image Container */}
              <div className="relative w-full pt-[100%] bg-[#090710] overflow-hidden">
                <img 
                  src={img.imageUrl} 
                  alt={img.prompt} 
                  className="absolute inset-0 w-full h-full object-cover transform group-hover:scale-105 transition-transform duration-500 ease-out"
                  loading="lazy"
                />
                
                {/* Overlay Controls */}
                <div className="absolute inset-0 bg-gradient-to-t from-[#090710]/90 via-[#090710]/30 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex flex-col justify-between p-6">
                  {/* Top badges */}
                  <div className="flex gap-2 justify-end">
                    <span className="px-3 py-1 rounded-full bg-black/60 backdrop-blur-md text-pink-300 text-xs font-semibold border border-pink-500/30">
                      {img.aspectRatio}
                    </span>
                    <span className="px-3 py-1 rounded-full bg-purple-600/80 backdrop-blur-md text-white text-xs font-semibold border border-white/10">
                      {img.style}
                    </span>
                  </div>

                  {/* Bottom Action Buttons */}
                  <div className="flex gap-3 justify-end">
                    <button 
                      onClick={() => handleDownload(img.imageUrl, img.prompt)}
                      className="btn-premium p-3 rounded-xl text-white shadow-lg flex items-center gap-2 text-sm font-bold border border-white/20"
                      title="Download Image"
                    >
                      <Download size={18} /> Download
                    </button>
                    <button 
                      onClick={() => handleShare(img._id)}
                      className="btn-secondary p-3 rounded-xl text-white shadow-lg flex items-center gap-2 text-sm font-bold border border-purple-800"
                      title="Copy URL"
                    >
                      <Share2 size={18} /> Share
                    </button>
                  </div>
                </div>
              </div>

              {/* Prompt Info */}
              <div className="p-6 flex-1 flex flex-col justify-between bg-purple-950/40 backdrop-blur-sm border-t border-purple-900/50">
                <p className="text-purple-100 text-sm line-clamp-3 font-medium leading-relaxed mb-4">
                  "{img.prompt}"
                </p>
                <div className="flex items-center justify-between text-xs text-purple-300/60 border-t border-purple-900/40 pt-4 mt-auto font-medium">
                  <span>Created</span>
                  <span>{new Date(img.createdAt).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' })}</span>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
